### ISSUE TITLE
swift单例

### ISSUE THREAD

**Issue by RtzX** [RickeyBoy/Rickey-iOS-Notes#1]
private let sharedInstance = MyManager()
class MyManager  {
    class var sharedManager : MyManager {
        return sharedInstance
    }
}

可以参考喵神的改进一下
class MyManager  {
    static let sharedInstance = MyManager()
    private init() {}
}

**Comment by RickeyBoy** [comment]
谢谢！
我又去看了一下喵神的文章，然后又拓展查了一些，已经更新了～
