### ISSUE TITLE
关于layer

### ISSUE THREAD

**Issue by Lyfei** [RickeyBoy/Rickey-iOS-Notes#12]
文中提到”在普通的 layer 绘制中，上层的 sublayer 会覆盖下层的 sublayer，下层 sublayer 绘制完之后就可以抛弃了“
这里的被抛弃是什么意思呢，view中的layer对象还是存在啊

**Comment by RickeyBoy** [comment]
抱歉刚看到，这里的 layer 抛弃指的是在内存中释放掉；通常是没有被强持有的 layer 对象
