### ISSUE TITLE
iOS 中的手势传递图片缺失

### ISSUE THREAD

**Issue by METISU** [RickeyBoy/Rickey-iOS-Notes#13]
hello，大佬，[iOS 中的手势传递图片缺失](https://github.com/RickeyBoy/Rickey-iOS-Notes/blob/master/Notes/Fundamental/iOS%20%E4%B8%AD%E7%9A%84%E6%89%8B%E5%8A%BF%E7%AE%A1%E7%90%86.md)这篇文章里面的图片好像丢了

**Comment by RickeyBoy** [comment]
这篇一直还没发布，之后发布了我会重新传一下
